env: "local"

server:
  port: "8080"

postgres:
  username: "postgres"
  password: "qwerty"
  dbname: "postgres"
  host: "localhost"
  port: "5436"
  sslmode: "disable"

token:
  access_ttl: 15m
  refresh_ttl: 24h